ACTION_MODEL_VERSION = "1.2.0"
COMPILER_VERSION = "1.2.0"
QUBO_SPEC_VERSION = "1.2.0"
CLASSICAL_REF_VERSION = "1.2.0"
FORMULATION_VERSION = "1.2.0"
DOWNSTREAM_POLICY_ID = "compound_obligation.v1"
DOWNSTREAM_POLICY_VERSION = "1.2.0"
REDUCTION_POLICY_ID = "kind_delay_compound_age_set.v2"
COEFFICIENT_UNITS = "seconds"
RISK_WEIGHT = 0.0
TOLERANCE_S = 1.0e-9
PAIR_ARRIVAL_TOLERANCE_S = 1.0e-9
EVALUATOR_RANK_TOLERANCE = 1.0e-12
EVALUATOR_VERSION = "1.2.0"
# Timing tolerance derived from simulator event time rounding (engine logs round t to 9 dp).
SIMULATOR_TIME_RESOLUTION_S = 1.0e-9
ACTION_TIMING_TOLERANCE_S = 1.0e-6  # 1000× resolution; declared a priori, not fitted to outcomes
REVIEW_PACKAGE_FORMAT_VERSION = "4.2.0"
INNER_MANIFEST_ALGORITHM_VERSION = "canonical_row_v1_bytes_path_sha256"
